name: PR Automation

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - feature/*  # feature/* 브랜치에 푸시될 때 자동 PR 생성

jobs:
  pr_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Add a comment on PR if tests fail
        if: failure()
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"body":"Tests failed. Please review the logs."}' \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments

  create_pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'  # push 이벤트 발생 시 실행
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: "auto-pr-branch-${{ github.sha }}"  # 새 브랜치 생성
          base: "master"  # PR 대상 브랜치
          title: "Automated PR from feature branch"
          body: "This PR was automatically generated from changes in feature branch."
